FROM gcfntnu/build-base:16.04

WORKDIR /opt
RUN git clone https://github.com/swiftbiosciences/primerclip.git
RUN cd primerclip && cp .stack-work/install/x86_64-linux/lts-11.0/8.2.2/bin/primerclip /usr/local/bin