FROM gcfntnu/r-base-conda:4.5.3

RUN conda install --quiet --yes \
    mscorefonts \
    font-ttf-ubuntu \
    r-argparse \
    r-optparse \
    r-tidyverse \
    r-data.table \
    r-ggpubr \
    r-cairo \
    r-hdf5r \
    r-rcurl \
    r-xml && \
    conda clean --all --yes
