FROM gcfntnu/python-base-conda:3.7

RUN conda install numpy \
 scipy \
 matplotlib \
 seaborn \
 plotnine \
 altair \
 vega_datasets \
 scikit-learn \
 h5py \
 click \
 pyyaml \
 R \
 rpy2 && \
 conda clean --all