ARG MINICONDA_VERSION=26.5.3
FROM anaconda/miniconda:${MINICONDA_VERSION}
# Keep compatibility with tools that expect Conda at /opt/conda.
RUN if [ ! -e /opt/conda ]; then ln -s "$(conda info --base)" /opt/conda; fi


ENV PYTHON_VER=3.10 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_CONFIG_FILE=/etc/pip.conf
COPY pip.conf /etc/pip.conf

RUN conda config --system --remove-key channels && \
    conda config --system --add channels defaults && \
    conda config --system --add channels bioconda && \
    conda config --system --add channels conda-forge && \
    conda config --system --set channel_priority strict && \
    conda config --system --set plugins.auto_accept_tos yes

RUN conda install --yes \
        python=${PYTHON_VER} \
        pip \
        git && \
    conda clean --all --yes
